# Generated by Django 6.1 on 2026-09-08 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interview Scheduled'), ('accepted', 'Accepted / Hired'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('remarks_history', models.TextField(blank=True, help_text='JSON list of status changes and employer remarks', null=True)),
                ('applicant_remarks_history', models.TextField(blank=True, null=True)),
                ('reviewed_by_employer_id', models.IntegerField(blank=True, null=True)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=255, null=True)),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='uploads/resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.applicantprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='CandidateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employability_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('feedback_message', models.TextField()),
                ('feedback_type', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to='accounts.applicantprofile')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='applications.application')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to='accounts.employerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('interview_type', models.CharField(default='video', help_text='in-person, phone, video', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='accounts.employerprofile')),
            ],
            options={
                'ordering': ['interview_date', 'start_time'],
            },
        ),
    ]
