# Generated by Django 6.1 on 2026-09-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='edu_match_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_decision',
            field=models.CharField(choices=[('none', 'Pending Employer Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected / Hired')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='employer_decision_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exp_match_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='application',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qualification_reason',
            field=models.TextField(blank=True, help_text='Internal evaluation and criteria match summary', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='qualification_status',
            field=models.CharField(choices=[('pending', 'Pending Evaluation'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='application',
            name='radar_rank',
            field=models.IntegerField(blank=True, help_text='Talent Radar Ranking position (e.g. 1 for Top Match)', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='sent_to_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='sent_to_employer_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='skills_match_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interview Scheduled'), ('selected', 'Selected / Hired'), ('accepted', 'Accepted / Hired'), ('rejected', 'Rejected'), ('pending', 'Pending Review'), ('reviewed', 'Reviewed')], default='applied', max_length=30),
        ),
    ]
