# Generated by Django 6.1 on 2026-09-09 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='created_by_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='min_experience_years',
            field=models.IntegerField(default=0, help_text='Minimum required experience years'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_education',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='EmployerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Position / Job Title', max_length=255)),
                ('description', models.TextField(help_text='Detailed job description and responsibilities')),
                ('skills_required', models.TextField(help_text='Comma-separated required skills')),
                ('experience_required', models.CharField(default='1-3 years', help_text='e.g. 2+ years, Entry Level, 5 years', max_length=100)),
                ('education_level', models.CharField(blank=True, help_text="e.g. Bachelor's Degree, Master's, High School", max_length=150, null=True)),
                ('certifications', models.TextField(blank=True, help_text='Required or preferred certifications', null=True)),
                ('location', models.CharField(default='Remote / Manila, Philippines', max_length=255)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full-time', max_length=50)),
                ('salary_range', models.CharField(blank=True, default='Negotiable', max_length=100, null=True)),
                ('vacancies_count', models.IntegerField(default=1, help_text='Number of candidates/applicants needed')),
                ('other_requirements', models.TextField(blank=True, help_text='Other specific requirements or qualifications', null=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Additional notes for Admin', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_admin_review', 'Under Admin Review'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('job_posted', 'Job Posted'), ('candidates_found', 'Candidates Found'), ('candidates_sent', 'Candidates Sent'), ('employer_review', 'Employer Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('admin_notes', models.TextField(blank=True, help_text='Feedback or remarks from Admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_requests', to='accounts.employerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='talent_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='jobs.employerrequest'),
        ),
    ]
