# Generated by Django 6.1 on 2026-09-15 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0002_jobposting_created_by_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='candidate_exports/')),
                ('filename', models.CharField(max_length=255)),
                ('google_drive_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_drive_view_link', models.URLField(blank=True, max_length=500, null=True)),
                ('google_drive_embed_link', models.URLField(blank=True, max_length=500, null=True)),
                ('total_candidates', models.IntegerField(default=0)),
                ('qualified_count', models.IntegerField(default=0)),
                ('not_qualified_count', models.IntegerField(default=0)),
                ('sent_to_employer', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_exports', to='accounts.employerprofile')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_candidate_batches', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_exports', to='jobs.jobposting')),
                ('talent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_exports', to='jobs.employerrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
