# Generated by Django 6.1 on 2026-09-08 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('answer_value', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='general', max_length=255)),
                ('score_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_answers', to='accounts.applicantprofile')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.qualification')),
            ],
            options={
                'ordering': ['created_at', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('job', 'Job Recommendation'), ('qualification', 'Qualification / Skill Path')], max_length=30)),
                ('recommendation_text', models.TextField(blank=True, null=True)),
                ('match_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_recommendations', to='accounts.applicantprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobposting')),
                ('qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.qualification')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
            },
        ),
    ]
