from django.db import models
from accounts.models import ApplicantProfile
from jobs.models import JobPosting, Qualification

class ChatbotAnswer(models.Model):
    """User answers to career questionnaire and assessment."""
    applicant = models.ForeignKey(ApplicantProfile, on_delete=models.CASCADE, related_name='chatbot_answers')
    qualification = models.ForeignKey(Qualification, on_delete=models.SET_NULL, null=True, blank=True)
    question_number = models.IntegerField()
    question_text = models.TextField()
    answer_text = models.TextField()
    answer_value = models.CharField(max_length=255, blank=True, null=True)
    category = models.CharField(max_length=255, default='general')
    score_value = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at', 'question_number']

    def __str__(self):
        return f"{self.applicant.user.full_name} - Q{self.question_number}: {self.score_value}pts"


class ChatbotRecommendation(models.Model):
    """Job and qualification recommendations generated by the career chatbot."""
    TYPE_CHOICES = (
        ('job', 'Job Recommendation'),
        ('qualification', 'Qualification / Skill Path'),
    )
    applicant = models.ForeignKey(ApplicantProfile, on_delete=models.CASCADE, related_name='chatbot_recommendations')
    job = models.ForeignKey(JobPosting, on_delete=models.SET_NULL, null=True, blank=True)
    qualification = models.ForeignKey(Qualification, on_delete=models.SET_NULL, null=True, blank=True)
    recommendation_type = models.CharField(max_length=30, choices=TYPE_CHOICES)
    recommendation_text = models.TextField(blank=True, null=True)
    match_score = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    is_selected = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-match_score', '-created_at']

    def __str__(self):
        return f"Chatbot Rec ({self.recommendation_type}) for {self.applicant.user.full_name}"
